### ISSUE TITLE
There are no instructions to run the app. 

### ISSUE THREAD

**Issue by joanmarcriera** [Renga2892/Person-Manager#1]

**Comment by Renga2892** [comment]
Seperate Readme files have been placed under each of the folders API Component and UI Component with build and run instructions. 

Let me if additional information is required. Thanks

**Comment by Renga2892** [comment]
Steps to build and run 
UI Comp : [Read Me](https://github.com/Renga2892/Person-Manager/blob/master/UI%20Component/README.md)
API comp : [Read Me](https://github.com/Renga2892/Person-Manager/blob/master/API%20Component/README.md)
